In [199]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

In [200]:
df = pd.read_csv("../Dataset/first_day_condition_activity.csv")
df = df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'])
df

00:00  01:00  02:00  03:00  04:00  05:00  06:00  07:00  08:00  09:00  ...  \
0     480    245    424    242    733     58    600    822   8804   6687  ...   
1    1532   1535    546    270   5704   9447  28610  19627  24468  30029  ...   
2    4408   2075    480    480    480    480    480    480    485  19090  ...   
3    2220    423    203     28    569    388  11980  17591  16399  22316  ...   
4    4835   3959   6457    807   1710    360    532    544    949   9951  ...   
5    4594    175    612    192    705    950    307  17239  14846   6839  ...   
6    1068    917    606    676    596  34090  17938  14812  28039  33920  ...   
7    1386    818   2135    974    241   1026   1812    688   1343   3193  ...   
8    2882    871    411   2840   1243    506   1093  11200  21471  25424  ...   
9     959    328   1629    641    440    548    346  12782  31878  24143  ...   
10   4126    135    258    816    602    465   6962    251    299   2538  ...   
11    706   2978    662     47    383    643   4018   5668   4839   3091  ...   
12    304    606    316   2275   4103  16187  14692   8681   1295   1176  ...   
13    112    340  10844  14721   8324   6310  26737  16852   5452    589  ...   
14   1078    224   1091    209    810    676   1440  43040  26806  12270  ...   
15    185     65    233    435     34    110     97    516  17279   6196  ...   
16  10407    813    383    897    581    314    604    383     30   1682  ...   
17   2732   5053   4862   4617   1969    633   2151   1670   2427   2457  ...   
18    122    280    399    607    284    580   9617   8456   6791   6327  ...   
19      0      0     69    163    535    340    518    260   2345   6019  ...   
20    155    145    354    126    124    120    624    241    804     13  ...   
21    804   1335    126   4253   1318    926   1901   4419    654    210  ...   
22    511   2325    580   2808      0   1677    307   3043   1769   2015  ...   

    15:00  16:00  17:00  18:00  19:00  20:00  21:00  22:00  23:00.6         Id  
0    4555  22090  23678  18468  15814   9859   7203   2791     4485  condition  
1   29557  23204  15980   9892   8865   2279  24152   1160     1537  condition  
2   62600  36530  40782  19567  10192  19797  33566  14499    19681  condition  
3    9726  13633   4575  22695  33011  25630  46288  39667     8929  condition  
4   62282  15433    806  14013  15777   8858   6839  16246    11040  condition  
5   26181   2735   5547  10942  30557   6484   4104   6206    11572  condition  
6   21393    560    688   1327  11248  10405  17734  11928    14132  condition  
7   34133  31975  24406  35533  25412  19397  13320  28790     2130  condition  
8    5402  12234  16475  15489  10836  10545  19962   8731     6113  condition  
9   37756  41776  48462  66345  45954  31324  26594  36162      750  condition  
10  33358   8707  10556   1501  25936  25566   5649   1337     9466  condition  
11  14796   9576  22022   4951  11075   7570  17972  10805    12628  condition  
12  25932  28933  11738  26836  25244  25728  15069  22032    14797  condition  
13   2464   2015      0   2952   5207   3079    414   1256        0  condition  
14  14438  14989  10289  24621  12819  10560  14107   4088     5281  condition  
15  53911  35782  33634  23551   4969  23026   6671   3486    23938  condition  
16  10873   7506  10807   9489   3672   1875   4451   2211     4848  condition  
17   6694   3415   7698   4454   5123   4959   2672     95       82  condition  
18  19867  12910   7818  10029   9269   7009   7239   2955     5624  condition  
19   6879   2596   4825  13817   6908   1076   7168    793     1088  condition  
20    458    296    396    721  10927    390   1838   3121        8  condition  
21  20727  19228  18710  11033  18247  15582  16356   9316      389  condition  
22  16658    388    562  24221  24274  12866  12158   7207    30018  condition  

[23 rows x 25 columns]

In [201]:
df_control = pd.read_csv("../Dataset/first_day_control_activity.csv")
df_control = df_control.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'])
df_control

00:00  01:00  02:00  03:00  04:00  05:00  06:00  07:00  08:00  09:00  ...  \
0     787    417    362   2021    622    290   1016   1597   4408  18645  ...   
1   19821    164    163    224    249    340   1434  35928  29828  18292  ...   
2       0      0      0      0      0      0      0      0      0  14477  ...   
3     324   1347   6075   1098    592   1804   2033    453    822   1002  ...   
4     324    326   1034     92    327   6107  42261  36681  19307  22059  ...   
5    4064    265    113    198    701    334    706   2300  28770  18972  ...   
6   43504    577   1258   1468    453   1932   1129   1657   3703  51484  ...   
7    2250   2637   8221   1076   1691    626   1265  21344  35969  38164  ...   
8     376    396    418    420    420    420    596    420    420    420  ...   
9     245    275    666    592    528    338    782    421    562    947  ...   
10   3244     58    154    353      0    141  12249  28460  15602  22109  ...   
11   2881    261    625    208     44    942  23825  14542  15416  12268  ...   
12    429    250   1799    498    893   6205  35263  26248  19721  30475  ...   
13   3113    921   1231    425   1605  21080  52445  37364  58310  80610  ...   
14    476   1014    209    670    552    499  36197  33290  19119  21688  ...   
15    786    976    676    712    349   1131  23373  26079  13369  22669  ...   
16   3599    559    258    593    389  14113  30561  22233  16731   6454  ...   
17  17634  14291  11727   3048    327    359    697    128   1148   1536  ...   
18   9970  21482    845   1673   1566    640   6894   2056    621   4133  ...   
19    802    688    431    971    286    479  18600  57786  29562  25868  ...   
20   8689  11925     23    148    679   1532     90   2582    663    930  ...   
21   3865   1308    926   1128   1242    642   1084   8661  35391  31015  ...   
22    338    405   2680    589    849    816  19223  13119  10567  13089  ...   
23  25370    978    647    307    334    317    621    208   1822  25465  ...   
24    682    422    165    290    387   5918  54406  22398  34821  28460  ...   
25    659    498   1389    644    967    683  37286  33460  33571  27345  ...   
26   5566   1044     76    396   1184    621   5976  33138  19621  17548  ...   
27  15671  25457    146    214   1972   8277   6730   7284  57561  23664  ...   
28  15932    485    231    495   1201   1011   2297    607    756  16301  ...   
29    842    979    924   1949   1648   1180    703   2177  18656  25444  ...   
30   1140    157     45    549    728   2031    610   1440  29570  46378  ...   
31   2844    228    291    545    415    982    337    656     58    767  ...   

    15:00  16:00  17:00   18:00  19:00   20:00  21:00  22:00  23:00.6       Id  
0   26062   7983  19517   36661  15938   11200  19040  11975    22024  control  
1   42468  42303  12644    9198  15428   19415  15960  16701    31403  control  
2   27835  14354   5810   22867  22095   25577  11650   9294    15370  control  
3   14515  18801  10116    5013  13454   26425  23871  16715    10516  control  
4   25939  21582  30911   11526  40735   52689  16615  24852     1981  control  
5   43664  25517  17048   15124  17203   56020  28938  32734    25648  control  
6   37019  28338  35513   14157  20276   21498  29806  19691    50203  control  
7   28109  33642  34846   49955  11876   10302  38631  23577    48596  control  
8   25854    246   1176   16087  13704    3392   2900  14816     4166  control  
9   52405  23831  33020   37708  36301   35694  33266  10719     5220  control  
10  19415  20680   1229    1460  12650    3493  10707   4526     7534  control  
11  19495    530  24311     522   7457     819   3389  10957     7501  control  
12  26660  14675  17686   40415  22206    8316   7373   2448     5215  control  
13  46175  18109  26292   38584  39306   13946  13876  12978    16520  control  
14  47667  32689   6888   54006  20093   38300  16166   9807     6837  control  
15  28894  28797  24227   23245  1

Code first day

In [202]:
data_new = {'sleep_time_activity':[] , 'day_time_activity':[], 'Id': []}
dfNew = pd.DataFrame(data_new)
dfNew

Empty DataFrame
Columns: [sleep_time_activity, day_time_activity, Id]
Index: []

In [203]:
sleep_time_activity = []
day_time_activity = []
id = []

def sumDf(df):
    for i in range(len(df['Id'])):
        #print((df.iloc[i].to_numpy())[:8])
        #print((df.iloc[i].to_numpy())[8:23])
        sum_sleeptime = sum((df.iloc[i].to_numpy())[:8]) + (df.iloc[i].to_numpy())[-2]
        print(sum((df.iloc[i].to_numpy())[8:23]))
        sum_daytime = sum((df.iloc[i].to_numpy())[8:23])
        sleep_time_activity.append(sum_sleeptime)
        day_time_activity.append(sum_daytime)
        id.append((df.iloc[i].to_numpy())[-1])
        #print(sum_sleeptime)
sumDf(df)
sumDf(df_control)

data_new['sleep_time_activity'] = sleep_time_activity
data_new['day_time_activity'] = day_time_activity
data_new['Id'] = id


217320
306335
372329
295691
246719
230754
284705
306687
201863
591740
160718
150118
352402
122358
195573
488584
102438
53272
192697
101365
102507
179983
234571
254452
321637
267528
240011
396275
437056
582173
475317
111789
392632
222149
184639
301566
643339
392966
292064
228332
300968
238456
428333
346560
335002
215425
666738
468253
506077
306761
426258
418850
204245
560218
155305


In [204]:
dfNew = pd.DataFrame(data_new)
dfNew

sleep_time_activity  day_time_activity         Id
0                  8089             217320  condition
1                 68808             306335  condition
2                 29044             372329  condition
3                 42331             295691  condition
4                 30244             246719  condition
5                 36346             230754  condition
6                 84835             284705  condition
7                 11210             306687  condition
8                 27159             201863  condition
9                 18423             591740  condition
10                23081             160718  condition
11                27733             150118  condition
12                61961             352402  condition
13                84240             122358  condition
14                53849             195573  condition
15                25613             488584  condition
16                19230             102438  condition
17                23769              53272  condition
18                25969             192697  condition
19                 2973             101365  condition
20                 1897             102507  condition
21                15471             179983  condition
22                41269             234571  condition
23                29136             254452    control
24                89726             321637    control
25                15370             267528    control
26                24242             240011    control
27                89133             396275    control
28                34329             437056    control
29               102181             582173    control
30                87706             475317    control
31                 7632             111789    control
32                 9067             392632    control
33                52193             222149    control
34                50829             184639    control
35                76800             301566    control
36               134704             643339    control
37                79744             392966    control
38                55243             292064    control
39                89388             228332    control
40                73027             300968    control
41                95065             238456    control
42                80855             428333    control
43                37888             346560    control
44                32170             335002    control
45                50936             215425    control
46                44065             666738    control
47                86302             468253    control
48                90534             506077    control
49                88756             306761    control
50                83745             426258    control
51                41873             418850    control
52                21459             204245    control
53                28548             560218    control
54                19517             155305    control

Five Days Code

In [205]:
df5days = pd.read_csv("../Dataset/five_day_activity.csv")
df5days = df5days.drop(columns=['Unnamed: 0'])
df5days

00:00  01:00  02:00  03:00  04:00  05:00  06:00  07:00  08:00  09:00  ...  \
0     480    245    424    242    733     58    600    822   8804   6687  ...   
1    1532   1535    546    270   5704   9447  28610  19627  24468  30029  ...   
2    4408   2075    480    480    480    480    480    480    485  19090  ...   
3    2220    423    203     28    569    388  11980  17591  16399  22316  ...   
4    4835   3959   6457    807   1710    360    532    544    949   9951  ...   
5    4594    175    612    192    705    950    307  17239  14846   6839  ...   
6    1068    917    606    676    596  34090  17938  14812  28039  33920  ...   
7    1386    818   2135    974    241   1026   1812    688   1343   3193  ...   
8    2882    871    411   2840   1243    506   1093  11200  21471  25424  ...   
9     959    328   1629    641    440    548    346  12782  31878  24143  ...   
10   4126    135    258    816    602    465   6962    251    299   2538  ...   
11    706   2978    662     47    383    643   4018   5668   4839   3091  ...   
12    304    606    316   2275   4103  16187  14692   8681   1295   1176  ...   
13    112    340  10844  14721   8324   6310  26737  16852   5452    589  ...   
14   1078    224   1091    209    810    676   1440  43040  26806  12270  ...   
15    185     65    233    435     34    110     97    516  17279   6196  ...   
16  10407    813    383    897    581    314    604    383     30   1682  ...   
17   2732   5053   4862   4617   1969    633   2151   1670   2427   2457  ...   
18    122    280    399    607    284    580   9617   8456   6791   6327  ...   
19      0      0     69    163    535    340    518    260   2345   6019  ...   
20    155    145    354    126    124    120    624    241    804     13  ...   
21    804   1335    126   4253   1318    926   1901   4419    654    210  ...   
22    511   2325    580   2808      0   1677    307   3043   1769   2015  ...   
23    787    417    362   2021    622    290   1016   1597   4408  18645  ...   
24  19821    164    163    224    249    340   1434  35928  29828  18292  ...   
25      0      0      0      0      0      0      0      0      0  14477  ...   
26    324   1347   6075   1098    592   1804   2033    453    822   1002  ...   
27    324    326   1034     92    327   6107  42261  36681  19307  22059  ...   
28   4064    265    113    198    701    334    706   2300  28770  18972  ...   
29  43504    577   1258   1468    453   1932   1129   1657   3703  51484  ...   
30   2250   2637   8221   1076   1691    626   1265  21344  35969  38164  ...   
31    376    396    418    420    420    420    596    420    420    420  ...   
32    245    275    666    592    528    338    782    421    562    947  ...   
33   3244     58    154    353      0    141  12249  28460  15602  22109  ...   
34   2881    261    625    208     44    942  23825  14542  15416  12268  ...   
35    429    250   1799    498    893   6205  35263  26248  19721  30475  ...   
36   3113    921   1231    425   1605  21080  52445  37364  58310  80610  ...   
37    476   1014    209    670    552    499  36197  33290  19119  21688  ...   
38    786    976    676    712    349   1131  23373  26079  13369  22669  ...   
39   3599    559    258    593    389  14113  30561  22233  16731   6454  ...   
40  17634  14291  11727   3048    327    359    697    128   1148   1536  ...   
41   9970  21482    845   1673   1566    640   6894   2056    621   4133  ...   
42    802    688    431    971    286    479  18600  57786  29562  25868  ...   
43   8689  11925     23    148    679   1532     90   2582    663    930  ...   
44   3865   1308    926   1128   1242    642   1084   8661  35391  31015  ...   
45    338    405   2680    589    849    816  19223  13119  10567  13089  ...   
46  25370    978    647    307    334    317    621    208   1822  25465  ...   
47    682    422    165    290    387   5918  54406  22398  34821  28460  ...   
48    659    498   1389    644    9

In [206]:
data_5day = {'5days_sleep_time_activity':[] , '5days_day_time_activity':[], 'Id': []}
dfavg = pd.DataFrame(data_5day)
dfavg

Empty DataFrame
Columns: [5days_sleep_time_activity, 5days_day_time_activity, Id]
Index: []

In [207]:
sleep_time_activity_5 = []
day_time_activity_5 = []
id_5 = []

def sum5days(df):
    for i in range(len(df['00:00'])):
        sum_sleeptime = 0
        sum_daytime = 0
        #print((df.iloc[i].to_numpy())[:8])
        #print((df.iloc[i].to_numpy())[8:23])
        for j in range(5):
            print((df.iloc[i].to_numpy())[(24 * j):(8 + 24 * j)])
            print((df.iloc[i].to_numpy())[-1 - (24 * j)])
            print((df.iloc[i].to_numpy())[8 + (24 * j):23 + (24 * j)])
            sum_sleeptime += sum((df.iloc[i].to_numpy())[(24 * j):(8 + 24 * j)]) + (df.iloc[i].to_numpy())[-1 - (24 * j)]
            sum_daytime += sum((df.iloc[i].to_numpy())[8 + (24 * j):23 + (24 * j)])
        #sum_sleeptime = sum((df.iloc[i].to_numpy())[:8]) + (df.iloc[i].to_numpy())[-2]
        print(sum((df.iloc[i].to_numpy())[8:23]))
        #sum_daytime = sum((df.iloc[i].to_numpy())[8:23])
        sleep_time_activity_5.append(sum_sleeptime/5)
        day_time_activity_5.append(sum_daytime/5)
        if i < 23:
            id_5.append('condition')
        else:
            id_5.append('control')
            
        #id.append((df.iloc[i].to_numpy())[-1])
        #print(sum_sleeptime)
sum5days(df5days)

data_5day['5days_sleep_time_activity'] = sleep_time_activity_5
data_5day['5days_day_time_activity'] = day_time_activity_5
data_5day['Id'] = id_5

[480 245 424 242 733  58 600 822]
1908
[ 8804  6687 23739 21117 14840 20882 16793  4555 22090 23678 18468 15814
  9859  7203  2791]
[4182 1335  661  125  759  271  386  340]
6674
[ 2193  9709 13730 25949 11544  2301   464  9641 10914 16567 17908 13408
 19987 10687  3492]
[6037 5918  463  197  222   35  118 1067]
5129
[13893 20380  4371  7000 20824 12470 13654 11093 12402 11533 26855  9421
  3605  2860  4798]
[ 166   55  245  391 1222  477  824  652]
2202
[ 7078  9496 13684 16049 11809 10704 17998  3762  9137  7469  7432  8670
  3432  3129  2638]
[166 160 747 315 589 581 581 592]
4072
[ 1014  8674 19068 22095 22062 42136 62091 47746 19932 68238 57597 53561
 14652  8412  3382]
217320
[ 1532  1535   546   270  5704  9447 28610 19627]
3231
[24468 30029 43085 19955 19048 30845 23816 29557 23204 15980  9892  8865
  2279 24152  1160]
[ 1151   243   555  1761  2912 11450 31214 21983]
579
[16881 30703 19239 20986 16557  8688 26858 29238 27710 18044 39671 14055
  7505  1563  1399]
[ 777  871 157

In [208]:
df5DaysAvg = pd.DataFrame(data_5day)
df5DaysAvg

5days_sleep_time_activity  5days_day_time_activity         Id
0                     10693.6                 228824.0  condition
1                     48771.2                 239278.2  condition
2                     43211.0                 317726.0  condition
3                     56892.4                 194298.2  condition
4                     31303.8                 200302.2  condition
5                     26634.2                 240767.8  condition
6                     61643.6                 335598.2  condition
7                     34374.2                 284320.6  condition
8                     42992.0                 203120.0  condition
9                     25811.0                 482765.0  condition
10                    50147.0                 153494.6  condition
11                    34576.6                 228420.4  condition
12                    62330.8                 291661.6  condition
13                    42878.0                  72237.4  condition
14                    42016.2                 164387.4  condition
15                    17938.8                 397321.0  condition
16                    24344.6                  85835.4  condition
17                    40038.4                  64142.0  condition
18                    17014.0                 189703.4  condition
19                    10301.8                  84496.8  condition
20                     4627.0                  91568.8  condition
21                    18023.6                 183974.4  condition
22                    29581.2                 235831.4  condition
23                    62703.4                 257546.4    control
24                    51929.0                 475113.4    control
25                    34742.8                 347817.0    control
26                    23481.0                 255676.4    control
27                    49904.8                 398723.0    control
28                   103205.0                 431101.8    control
29                   115329.4                 479807.0    control
30                   124525.0                 467588.6    control
31                    19149.8                 169119.2    control
32                    35635.0                 293293.2    control
33                    37543.8                 233625.8    control
34                    30825.2                 227922.0    control
35                    28298.2                 246814.8    control
36                    97899.4                 471340.6    control
37                    64710.4                 373257.6    control
38                    50966.2                 343819.2    control
39                    54870.4                 304521.0    control
40                    54821.6                 327886.0    control
41                    79226.0                 233218.6    control
42                    62504.0                 480728.2    control
43                   129507.8                 260240.4    control
44                    41799.6                 326000.6    control
45                    43280.4                 249467.8    control
46                    65133.6                 584654.0    control
47                    67783.8                 462165.4    control
48                   111668.2                 464377.6    control
49                    84647.2                 331799.6    control
50                    96948.4                 343388.2    control
51                    60045.6                 327889.8    control
52                    45442.2                 284416.2    control
53                    60903.2                 392232.0    control
54                    47928.8                 151957.4    control

In [209]:
#df5DaysAvg.to_csv('../Dataset/5_days_sleep_pattern_1.csv')