In [392]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense

In [393]:
ml_df = pd.read_csv(
    "../Dataset/for training/4_feat_wo_fill.csv")
ml_df.drop(["Unnamed: 0"], axis=1, inplace=True)
ml_df['Id'] = ['condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'control', 'control',
            'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control']
ml_df

gender  age  5days_sleep_time_activity  5days_day_time_activity         Id
0        2   37                    10693.6                 228824.0  condition
1        2   42                    48771.2                 239278.2  condition
2        1   47                    43211.0                 317726.0  condition
3        2   27                    56892.4                 194298.2  condition
4        2   52                    31303.8                 200302.2  condition
5        1   37                    26634.2                 240767.8  condition
6        1   22                    61643.6                 335598.2  condition
7        2   27                    34374.2                 284320.6  condition
8        2   47                    42992.0                 203120.0  condition
9        2   47                    25811.0                 482765.0  condition
10       1   47                    50147.0                 153494.6  condition
11       2   42                    34576.6                 228420.4  condition
12       2   37                    62330.8                 291661.6  condition
13       1   62                    42878.0                  72237.4  condition
14       2   57                    42016.2                 164387.4  condition
15       1   47                    17938.8                 397321.0  condition
16       1   52                    24344.6                  85835.4  condition
17       2   42                    40038.4                  64142.0  condition
18       2   52                    17014.0                 189703.4  condition
19       1   32                    10301.8                  84496.8  condition
20       2   37                     4627.0                  91568.8  condition
21       1   67                    18023.6                 183974.4  condition
22       1   32                    29581.2                 235831.4  condition
23       2   27                    62703.4                 257546.4    control
24       1   32                    51929.0                 475113.4    control
25       2   32                    34742.8                 347817.0    control
26       1   27                    23481.0                 255676.4    control
27       1   32                    49904.8                 398723.0    control
28       1   27                   103205.0                 431101.8    control
29       1   22                   115329.4                 479807.0    control
30       2   42                   124525.0                 467588.6    control
31       2   32                    19149.8                 169119.2    control
32       1   32                    35635.0                 293293.2    control
33       1   47                    37543.8                 233625.8    control
34       1   62                    30825.2                 227922.0    control
35       1   52                    28298.2                 246814.8    control
36       1   52                    97899.4                 471340.6    control
37       1   47                    64710.4                 373257.6    control
38       2   42                    50966.2                 343819.2    control
39       1   47                    54870.4                 304521.0    control
40       2   22                    54821.6                 327886.0    control
41       1   52                    79226.0                 233218.6    control
42       1   37                    62504.0                 480728.2    control
43       1   52                   129507.8                 260240.4    control
44       1   27                    41799.6                 326000.6    control
45       1   22                    43280.4                 249467.8    control
46       2   22                    65133.6                 584654.0    control
47       1   67                    67783.8                 462165.4    control
48       1   37                   111668.2                 464377.6    control
49       2   52                    84647.2            

In [394]:
import math
from matplotlib.colors import ListedColormap

In [395]:
x = [] 
y = [] 
count  = 0
count_g = 0
count_o = 0

for i in range(len(ml_df["Id"])):
    
    if ml_df["Id"][i] == "condition":
        x.append(1)
        y.append([ml_df["5days_sleep_time_activity"][i],
                           ml_df["5days_day_time_activity"][i] ,ml_df["age"][i]])
                           
    
    elif ml_df["Id"][i] == "control":
        x.append(0)
        y.append([ml_df["5days_sleep_time_activity"][i],
                           ml_df["5days_day_time_activity"][i], ml_df["age"][i]])
    

    
print(f'Select: {len(y)} set')
y = np.array(y)
x = np.array(x)

print(y)
print(x)

Select: 55 set
[[1.069360e+04 2.288240e+05 3.700000e+01]
 [4.877120e+04 2.392782e+05 4.200000e+01]
 [4.321100e+04 3.177260e+05 4.700000e+01]
 [5.689240e+04 1.942982e+05 2.700000e+01]
 [3.130380e+04 2.003022e+05 5.200000e+01]
 [2.663420e+04 2.407678e+05 3.700000e+01]
 [6.164360e+04 3.355982e+05 2.200000e+01]
 [3.437420e+04 2.843206e+05 2.700000e+01]
 [4.299200e+04 2.031200e+05 4.700000e+01]
 [2.581100e+04 4.827650e+05 4.700000e+01]
 [5.014700e+04 1.534946e+05 4.700000e+01]
 [3.457660e+04 2.284204e+05 4.200000e+01]
 [6.233080e+04 2.916616e+05 3.700000e+01]
 [4.287800e+04 7.223740e+04 6.200000e+01]
 [4.201620e+04 1.643874e+05 5.700000e+01]
 [1.793880e+04 3.973210e+05 4.700000e+01]
 [2.434460e+04 8.583540e+04 5.200000e+01]
 [4.003840e+04 6.414200e+04 4.200000e+01]
 [1.701400e+04 1.897034e+05 5.200000e+01]
 [1.030180e+04 8.449680e+04 3.200000e+01]
 [4.627000e+03 9.156880e+04 3.700000e+01]
 [1.802360e+04 1.839744e+05 6.700000e+01]
 [2.958120e+04 2.358314e+05 3.200000e+01]
 [6.270340e+04 2.57

In [396]:
model = Sequential()
model.add(Dense(36, input_dim = 3, activation = 'relu'))
model.add(Dense(18, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [397]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [398]:
model.fit(y, x, epochs=55, batch_size=10)

Epoch 1/55
6/6 [==============================] - 0s 1ms/step - loss: 33507.5273 - accuracy: 0.5818
Epoch 2/55
6/6 [==============================] - 0s 1ms/step - loss: 25413.0039 - accuracy: 0.5818
Epoch 3/55
6/6 [==============================] - 0s 1ms/step - loss: 16957.9883 - accuracy: 0.5818
Epoch 4/55
6/6 [==============================] - 0s 3ms/step - loss: 9932.8896 - accuracy: 0.5818
Epoch 5/55
6/6 [==============================] - 0s 1ms/step - loss: 1916.9073 - accuracy: 0.6182
Epoch 6/55
6/6 [==============================] - 0s 2ms/step - loss: 4124.0942 - accuracy: 0.4182
Epoch 7/55
6/6 [==============================] - 0s 2ms/step - loss: 1248.3080 - accuracy: 0.5455
Epoch 8/55
6/6 [==============================] - 0s 1ms/step - loss: 1801.7581 - accuracy: 0.5818
Epoch 9/55
6/6 [==============================] - 0s 2ms/step - loss: 832.1519 - accuracy: 0.4364
Epoch 10/55
6/6 [==============================] - 0s 1ms/step - loss: 707.9860 - accuracy: 0.5273
Epoch 11

In [399]:
_, accuracy = model.evaluate(y, x)
print('Accuracy: %.2f' % (accuracy*100))

2/2 [==============================] - 0s 2ms/step - loss: 94.8642 - accuracy: 0.7091
Accuracy: 70.91


In [400]:
predictions = model.predict(y)
rounded = [round(y[0]) for y in predictions]