In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

from sklearn.metrics import RocCurveDisplay
from sklearn import preprocessing
from tensorflow import keras

from hyperopt import hp
from hyperopt import fmin, tpe


In [2]:
ml_df = pd.read_csv(
    "../Dataset/for training/4_feat_wo_fill.csv")
ml_df.drop(["Unnamed: 0"], axis=1, inplace=True)
ml_df['Id'] = ['condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'condition', 'control', 'control',
               'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control', 'control']
ml_df


gender  age  5days_sleep_time_activity  5days_day_time_activity         Id
0        2   37                    10693.6                 228824.0  condition
1        2   42                    48771.2                 239278.2  condition
2        1   47                    43211.0                 317726.0  condition
3        2   27                    56892.4                 194298.2  condition
4        2   52                    31303.8                 200302.2  condition
5        1   37                    26634.2                 240767.8  condition
6        1   22                    61643.6                 335598.2  condition
7        2   27                    34374.2                 284320.6  condition
8        2   47                    42992.0                 203120.0  condition
9        2   47                    25811.0                 482765.0  condition
10       1   47                    50147.0                 153494.6  condition
11       2   42                    34576.6                 228420.4  condition
12       2   37                    62330.8                 291661.6  condition
13       1   62                    42878.0                  72237.4  condition
14       2   57                    42016.2                 164387.4  condition
15       1   47                    17938.8                 397321.0  condition
16       1   52                    24344.6                  85835.4  condition
17       2   42                    40038.4                  64142.0  condition
18       2   52                    17014.0                 189703.4  condition
19       1   32                    10301.8                  84496.8  condition
20       2   37                     4627.0                  91568.8  condition
21       1   67                    18023.6                 183974.4  condition
22       1   32                    29581.2                 235831.4  condition
23       2   27                    62703.4                 257546.4    control
24       1   32                    51929.0                 475113.4    control
25       2   32                    34742.8                 347817.0    control
26       1   27                    23481.0                 255676.4    control
27       1   32                    49904.8                 398723.0    control
28       1   27                   103205.0                 431101.8    control
29       1   22                   115329.4                 479807.0    control
30       2   42                   124525.0                 467588.6    control
31       2   32                    19149.8                 169119.2    control
32       1   32                    35635.0                 293293.2    control
33       1   47                    37543.8                 233625.8    control
34       1   62                    30825.2                 227922.0    control
35       1   52                    28298.2                 246814.8    control
36       1   52                    97899.4                 471340.6    control
37       1   47                    64710.4                 373257.6    control
38       2   42                    50966.2                 343819.2    control
39       1   47                    54870.4                 304521.0    control
40       2   22                    54821.6                 327886.0    control
41       1   52                    79226.0                 233218.6    control
42       1   37                    62504.0                 480728.2    control
43       1   52                   129507.8                 260240.4    control
44       1   27                    41799.6                 326000.6    control
45       1   22                    43280.4                 249467.8    control
46       2   22                    65133.6                 584654.0    control
47       1   67                    67783.8                 462165.4    control
48       1   37                   111668.2                 464377.6    control
49       2   52                    84647.2            

In [3]:
x = []
y = []
count = 0
count_g = 0
count_o = 0

for i in range(len(ml_df["Id"])):

    if ml_df["Id"][i] == "condition":
        y.append([1])
        x.append([ml_df["5days_sleep_time_activity"][i],
                  ml_df["5days_day_time_activity"][i], ml_df["age"][i]])

    elif ml_df["Id"][i] == "control":
        y.append([0])
        x.append([ml_df["5days_sleep_time_activity"][i],
                  ml_df["5days_day_time_activity"][i], ml_df["age"][i]])


print(f'Select: {len(y)} set')
y = np.array(y)
x = np.array(x)



Select: 55 set
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[1.069360e+04 2.288240e+05 3.700000e+01]
 [4.877120e+04 2.392782e+05 4.200000e+01]
 [4.321100e+04 3.177260e+05 4.700000e+01]
 [5.689240e+04 1.942982e+05 2.700000e+01]
 [3.130380e+04 2.003022e+05 5.200000e+01]
 [2.663420e+04 2.407678e+05 3.700000e+01]
 [6.164360e+04 3.355982e+05 2.200000e+01]
 [3.437420e+04 2.843206e+05 2.700000e+01]
 [4.299200e+04 2.031200e+05 4.700000e+01]
 [2.581100e+04 4.827650e+05 4.700000e+01]
 [5.014700e+04 1.534946e+05 4.700000e+01]
 [3.457660e+04 2.284204e+05 4.200000e+01]
 [6.233080e+04 2.916616e+05 3.700000e+01]
 [4.287800e+04 7.223740e+04 6.200000e+01]
 [4.201620e+04 1.643874e+05 5.700000e+01]
 [1.793880e+04 3.973210e+05 4.700000e+01]
 [2.434460e+04 8.583540e+04 5.200000e

In [4]:
# Add noisy features
random_state = np.random.RandomState(0)


# Train Test split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=random_state)


In [5]:
def classifier_modeling():
    model = Sequential()
    model.add(Dense(8, input_shape=(3,), activation='relu'))
    model.add(Dense(4, activation='relu'))
    model.add(Dense(2, activation='sigmoid'))
    model.compile(loss='binary_crossentropy',
                  optimizer='adam', metrics=['accuracy'])
    return model


In [6]:
classifier_modeling()

In [7]:
from hyperopt.pyll.base import scope
from hyperopt import STATUS_OK
#quniform returns float, some parameters require int; use this to force int
space = {'rate': hp.uniform('rate', 0.01, 0.5),
         'unit1': scope.int(hp.quniform('unit1', 10, 200, 10)),
         'unit2': scope.int(hp.quniform('unit2', 10, 200, 10)),
         'unit3': scope.int(hp.quniform('unit3', 10, 200, 10)),
         'batch_size':
         scope.int(hp.quniform('batch_size', 100, 250, 25)),
         'layers': scope.int(hp.quniform('layers', 1, 3, 1)),
         'activation': hp.choice('activation', ['relu', 'softmax', 'sigmoid']),
        'optimizer': hp.choice('optimizer', ['adam', 'adadelta', 'sgd', 'RMSprop'])

        }


In [8]:
def f_nn(params):

    model = classifier_modeling()

    if params['layers'] == 1:
        model.add(Dense(units=params['unit1'],
                        input_shape=(x_train.shape[1],), activation=params['activation']))

        model.add(Dropout(rate=params['rate']))
    else:
        # First layer specifies input_shape and returns sequences
        model.add(Dense(units=params['unit1'],
                        input_shape=(x_train.shape[1],), activation=params['activation']))
        model.add(Dropout(rate=params['rate']))

        # Middle layers return sequences
        for i in range(params['layers']-1):
            model.add(
                Dense(units=params['unit'+str(i+2)], activation=params['activation']))
        model.add(Dropout(rate=params['rate']))

    model.add(Dense(2, activation='softmax'))
    model.compile(optimizer=params['optimizer'], loss='mean_squared_error')

    # es = EarlyStopping(monitor='val_loss', mode='min',
    #                    verbose=1, patience=15)
    result = model.fit(x_train, y_train,
                       verbose=0,
                       validation_split=0.1,
                       batch_size=params['batch_size'],
                       epochs=200)

    # Get the lowest validation loss of the training epochs
    validation_loss = np.amin(result.history['val_loss'])
    print('Best validation loss of epoch:', validation_loss)

    return {'loss': validation_loss,
            'status': STATUS_OK,
            'model': model,
            'params': params}


In [9]:
from hyperopt import Trials

trials = Trials()
best = fmin(f_nn,
            space,
            algo=tpe.suggest,
            max_evals=5,
            trials=trials)


Best validation loss of epoch:                       
0.2500000596046448                                   
Best validation loss of epoch:                                                 
0.2500074505805969                                                             
Best validation loss of epoch:                                                 
0.2500000596046448                                                             
Best validation loss of epoch:                                                 
0.25                                                                           
Best validation loss of epoch:                                                 
0.2507583796977997                                               
100%|██████████| 5/5 [00:31<00:00,  6.30s/trial, best loss: 0.25]


In [10]:
best_model = trials.results[np.argmin([r['loss'] for r in 
    trials.results])]['model']
best_params = trials.results[np.argmin([r['loss'] for r in 
    trials.results])]['params']
worst_model = trials.results[np.argmax([r['loss'] for r in 
    trials.results])]['model']
worst_params = trials.results[np.argmax([r['loss'] for r in 
    trials.results])]['params']

print(best_params)

{'activation': 'sigmoid', 'batch_size': 125, 'layers': 2, 'optimizer': 'adam', 'rate': 0.20734511493504382, 'unit1': 50, 'unit2': 60, 'unit3': 120}
